### PR TITLE
Code coverage

### PR DESCRIPTION
**Pull request by astorije**
Code coverage can be run via `npm run coverage`.
The coveralls badge is updated after Travis builds.

### CODE REVIEW

**Comment by astorije** [comment]
Small and trivial PR, can this be merged please?

By the way, the annoying comments Coveralls makes at every PR [have already been disabled](https://github.com/w3c/specberus/pull/158#issuecomment-78186915) before the fact...

**Comment by astorije** [comment]
Mmmmmh, what the with the history?!

@tripu, can I fix that and merge after fixing if you are happy with the 2 commits?

**Comment by astorije** [comment]
(or merge yourself after I fix the history...)

**Comment by tripu** [comment]
@astorije That was me trying to squash commits after rebasing your branch :P

Yes please, fix and merge if you have a minute. I'll ask you about squashing commits in a few hours&hellip;

**Comment by tripu** [comment]
Thank you for tweaking Coveralls settings, btw, @astorije!

**Comment by astorije** [comment]
Here you go!
It took me a minute before seeing that you merged a branch with itself, I didn't know git would even let you do that :D

You don't need to squash the 2 commits, I split my changes in 2 on purpose (I usually always use `git add -p` instead of `git add` to pick exactly what I want in the commits and try to send meaningful commits, and squash when they aren't and I can squash).

**Comment by astorije** [comment]
So to help answer the question you didn't even ask yet, 3 things I often use:

- `git add -p` (I use it so often that I aliased it to `git ap`)
- `git rebase -i HEAD~n` to rebase the last `n` commits, using `fixup` to squash some
- ... `git reflog` when I reeeally mess up with my rebases and need to literally go back in time :D

**Pull request merged**
