### PR TITLE
chore: add lint-staged

### PR DESCRIPTION
**Pull request by nschonni**
- Expand and fix cspell globs
- Expand and fix ESLint globs

Didn't add the prettier part, becuase it was a larger diff

### CODE REVIEW

**Comment by nschonni** [comment]
@jennyliang220 I gave this one a rebase for the conflict

**Comment by jennyliang220** [comment]
Hi, @nschonni, this PR is pending because of the additional rules in `.eslintrc.js`. The goal is to have no exceptions, I'll need some time to fix all the warnings and errors that the lint is complaining about.

**Comment by nschonni** [comment]
OK, I removed all the "off" with "warn", and fixed the straight forward issues

**Comment by nschonni** [comment]
Actually I don't think some of the test changes are right, so flipped back to draft

**Comment by nschonni** [comment]
Here are the remaining warnings
```
Z:\echidna\test\lib\fake-http-services.js
   9:24  warning  Unexpected unnamed function  func-names
  11:33  warning  Unexpected unnamed function  func-names
  20:31  warning  Unexpected unnamed function  func-names
  22:40  warning  Unexpected unnamed function  func-names
  34:27  warning  Unexpected unnamed function  func-names
  47:28  warning  Unexpected unnamed function  func-names
  49:37  warning  Unexpected unnamed function  func-names

Z:\echidna\test\lib\htmltemplate.js
  46:10  warning  Unexpected unnamed function  func-names

Z:\echidna\test\lib\testserver.js
   27:20  warning  Unexpected unnamed function   func-names
  103:3   warning  Unexpected console statement  no-console
  104:3   warning  Unexpected console statement  no-console
  126:20  warning  Unexpected unnamed function   func-names
  145:5   warning  Unexpected console statement  no-console
  148:3   warning  Unexpected console statement  no-console
  149:3   warning  Unexpected console statement  no-console
  150:3   warning  Unexpected console statement  no-console
  153:23  warning  Unexpected unnamed function   func-names
  160:26  warning  Unexpected unnamed function   func-names

Z:\echidna\test\lib\utils.js
  52:16  warning  Unexpected unnamed function  func-names

Z:\echidna\test\test-json-http-service.js
  27:9  warning  Unexpected unnamed function  func-names
  31:9  warning  Unexpected unnamed function  func-names
  35:9  warning  Unexpected unnamed function  func-names

Z:\echidna\test\views\behaviour.js
   71:19  warning  Unexpected use of 'location'
                   no-restricted-globals
   85:5   warning  Unexpected alert
                   no-alert
   91:5   warning  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype
                   guard-for-in
   91:5   warning  for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array  no-restricted-syntax
  103:3   warning  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype
                   guard-for-in
  103:3   warning  for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array  no-restricted-syntax
  105:29  warning  Unexpected use of 'location'
                   no-restricted-globals
  110:7   warning  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype
                   guard-for-in
  110:7   warning  for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array  no-restricted-syntax
  144:27  warning  Unexpected unnamed function
                   func-names
  155:26  warning  Unexpected unnamed function
                   func-names
  161:24  warning  Unexpected unnamed function
                   func-names

✖ 34 problems (0 errors, 34 warnings)
```

**Pull request closed without merging**
