### PR TITLE
Update npm dependencies

### PR DESCRIPTION
**Pull request by tripu**
&hellip;running [updtr](https://github.com/peerigon/updtr) (and, while at it, enable [growl notifications](https://mochajs.org/#mocha-opts) in mocha and turn on coloured output explicitly).

### CODE REVIEW

**Comment by plehegar** [comment]
LGTM

**Comment by astorije** [comment]
I suggest you go to [chai-immutable v1.5.3](https://github.com/astorije/chai-immutable/releases/tag/v1.5.3) as some long-time bugs were fixed there :-) Here is [the diff](https://github.com/astorije/chai-immutable/compare/v1.2.0...v1.5.3).

Also, as you are reaching a critical size and a stable product, you might want to change your dependency version policy to be a bit more strict. I would either fix everything, or at least everything but the patch number (only major number is fixed at the moment.
But that's just my advice, you do what you want :-)

**Comment by tripu** [comment]
@astorije: good idea&nbsp;&mdash;&nbsp;done!

**Comment by deniak** [comment]
LGTM. @tripu feel free to rebase and merge.

**Pull request merged**
